spring:
  profiles:
    active: test

---
spring:
  profiles: local
  datasource:
    platform: h2
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:tcp://localhost:9092/mem:woowa-quiz
      username: sa
      password:
  jpa:
    database-platform: H2
    show-sql: false
    hibernate:
      ddl-auto: update
---
spring:
  profiles: test
  datasource:
    platform: h2
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:woowa-quiz
      username: sa
      password:
  jpa:
    database-platform: H2
    show-sql: false
    hibernate:
      ddl-auto: update