spring:
  profiles:
    active: local
---
spring.profiles: local
spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:woowa-quiz;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  jpa:
    properties:
      hibernate:
        format_sql: false
        hbm2ddl:
          auto: update