spring:
  profiles:
    active: local
  jpa:
    show-sql: true
    open-in-view: false

---
spring:
  profiles: local
  datasource:
    hikari:
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: jdbc:mariadb://localhost:3306/woowa-quiz
      username: root
      password: root
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

---
spring:
  profiles: test
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:woowa-quiz;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL
      username: sa
      password:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: false
        hbm2ddl:
          auto: create-drop
  h2:
    console:
      enabled: true